{% set name = "dtool_annotation" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-annotation/dtool-annotation-{{ version }}.tar.gz
  sha256: 6533c4572534f31bd9ea371e898cd88e79db946f86c1c017268187ee79c8ff33

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - dtool_cli
    - dtoolcore >=3.13.0
    - python >=3.6

test:
  imports:
    - dtool_annotation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-annotation
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Add ability to annotate datasets using the dtool CLI
  description: |
    dtool CLI commands for working with per dataset metadata (annotations)
  doc_url: https://github.com/jic-dtool/dtool-annotation
  dev_url: https://github.com/jic-dtool/dtool-annotation

extra:
  recipe-maintainers:
    - jan-janssen
    - tjelvar-olsson
